import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './fonts.css';
import React from "react";
import NextUiProvider from "@/app/NextUIProvider";
import MainNavbar from "@/components/navbar";
import { UserProvider } from '@/context/UserProvider';
import { ToasterProvider } from '@/context/ToasterContext';
import { QueryProvider } from './QueryClientProvider'
import { FriendsProvider } from "@/context/FriendsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${inter.className} relative`  } >
        <NextUiProvider >
            <ToasterProvider>
                <QueryProvider>
                    <UserProvider>
                      <FriendsProvider>
                        <MainNavbar/>
                        {children}
                      </FriendsProvider>
                    </UserProvider>
                </QueryProvider>
            </ToasterProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
